/* Build-time preprocessing for "real faces" mode.
 *
 * For each image in the source folder, runs MediaPipe Face Landmarker
 * (IMAGE mode, in headless Chrome — same model the game uses on the player),
 * then:
 *  - extracts the 52 blendshape coefficients  -> the photo's scoring target
 *  - extracts subsampled landmarks            -> for the mesh-scan animation
 *  - crops a normalized square around the face -> public/faces/faceNN.jpg (512px)
 * and writes src/realFaces.ts with the metadata.
 *
 * Run: node scripts/prep-faces.mjs ["/path/to/source folder"]
 */
import { chromium } from 'playwright-core';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, extname } from 'node:path';

const SRC = process.argv[2] ?? '/Users/felipepereira/Desktop/real faces';
const OUT_DIR = 'public/faces';
const EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp']);

const files = readdirSync(SRC).filter((f) => EXTS.has(extname(f).toLowerCase())).sort();
console.log(`${files.length} candidate images`);

const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage();
page.on('console', (m) => { if (m.type() === 'error') console.log(`[console] ${m.text()}`); });
await page.goto('http://localhost:5199/');

await page.evaluate(async () => {
  const vision = await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/+esm');
  const fileset = await vision.FilesetResolver.forVisionTasks(
    'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm',
  );
  window.__fl = await vision.FaceLandmarker.createFromOptions(fileset, {
    baseOptions: {
      modelAssetPath:
        'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',
      delegate: 'GPU',
    },
    runningMode: 'IMAGE',
    numFaces: 4,
    outputFaceBlendshapes: true,
  });
});

rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const meta = [];
for (const file of files) {
  const mime = extname(file).toLowerCase() === '.png' ? 'image/png' : 'image/jpeg';
  const dataUrl = `data:${mime};base64,${readFileSync(join(SRC, file)).toString('base64')}`;

  const result = await page.evaluate(async (src) => {
    const img = new Image();
    img.src = src;
    await img.decode();
    const res = window.__fl.detect(img);
    if (res.faceLandmarks.length === 0) return null;

    // Dominant face = largest landmark bounding box
    let best = 0, bestArea = 0;
    res.faceLandmarks.forEach((lm, i) => {
      const xs = lm.map((p) => p.x), ys = lm.map((p) => p.y);
      const area = (Math.max(...xs) - Math.min(...xs)) * (Math.max(...ys) - Math.min(...ys));
      if (area > bestArea) { bestArea = area; best = i; }
    });

    const lm = res.faceLandmarks[best];
    const xs = lm.map((p) => p.x * img.naturalWidth);
    const ys = lm.map((p) => p.y * img.naturalHeight);
    const minX = Math.min(...xs), maxX = Math.max(...xs);
    const minY = Math.min(...ys), maxY = Math.max(...ys);

    // Normalized square crop: face + 45% margin, clamped to the image
    let size = Math.max(maxX - minX, maxY - minY) * 1.45;
    size = Math.min(size, img.naturalWidth, img.naturalHeight);
    let sx = (minX + maxX) / 2 - size / 2;
    let sy = (minY + maxY) / 2 - size / 2;
    sx = Math.max(0, Math.min(sx, img.naturalWidth - size));
    sy = Math.max(0, Math.min(sy, img.naturalHeight - size));

    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = 512;
    const ctx = canvas.getContext('2d');
    ctx.drawImage(img, sx, sy, size, size, 0, 0, 512, 512);

    const shape = {};
    for (const b of res.faceBlendshapes[best].categories) {
      if (b.score >= 0.015 && b.categoryName !== '_neutral') {
        shape[b.categoryName] = Math.round(b.score * 1000) / 1000;
      }
    }

    const step = Math.max(1, Math.floor(lm.length / 80));
    const pts = [];
    for (let i = 0; i < lm.length; i += step) {
      pts.push([
        Math.round(((xs[i] - sx) / size) * 1000) / 1000,
        Math.round(((ys[i] - sy) / size) * 1000) / 1000,
      ]);
    }

    return { shape, pts, jpeg: canvas.toDataURL('image/jpeg', 0.85) };
  }, dataUrl);

  if (!result) {
    console.log(`SKIP  ${file} — no face detected`);
    continue;
  }
  const name = `face${String(meta.length + 1).padStart(2, '0')}.jpg`;
  writeFileSync(join(OUT_DIR, name), Buffer.from(result.jpeg.split(',')[1], 'base64'));
  meta.push({ img: name, shape: result.shape, pts: result.pts });
  const strong = Object.entries(result.shape).filter(([, v]) => v > 0.4).map(([k]) => k).slice(0, 4);
  console.log(`OK    ${file} -> ${name} (${strong.join(', ') || 'subtle expression'})`);
}

await browser.close();

const ts = `// Generated by scripts/prep-faces.mjs — do not edit by hand.
import type { Shape } from './blendshapes';

export interface RealFace {
  img: string;
  shape: Shape;
  /** Subsampled face landmarks in cropped-image space (0..1). */
  pts: Array<[number, number]>;
}

export const REAL_FACES: RealFace[] = ${JSON.stringify(meta)};
`;
writeFileSync('src/realFaces.ts', ts);
console.log(`\nWrote ${meta.length} faces -> ${OUT_DIR}/ and src/realFaces.ts`);
